
team-service:
  url: http://TEAM-SERVICE/team/
spring:
  kafka:
    producer:
      bootstrap-servers: 192.168.0.102:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer:  org.springframework.kafka.support.serializer.JsonSerializer


